[build]
  base = "."
  command = "npm ci --prefix client && npm ci --prefix server && cd client && npm run build && cd .."
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "development"

[functions]
  directory = "server/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
